name: ci
on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - run: |
         echo "${{github.event.pull_request.head.sha}}"
         echo "${{github.event.pull_request.number}}"
         


