name: ci
on:
  pull_request_target:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:   
      - run: |
         echo "${{github.event.pull_request.head.sha}}"
         echo "${{github.event.pull_request.number}}"
         echo "repo=$GITHUB_REPOSITORY" >> $GITHUB_ENV
         
      - name: Auto merge
        run: |
          curl -X PUT -H  "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" \
          https://api.github.com/repos/${{env.repo}}/pulls/${{github.event.pull_request.number}}/merge \
           -d '{"commit_title":"fake title","commit_message":"somethingssd dsd","sha":"${{github.event.pull_request.head.sha}}"}'
          
         


